version: '3'
services:
  mongo:
    image: mongo:3.6
    restart: on-failure
    ports:
      - 27017:27017
  server:
    build:
      context: .
      args:
        - DLIB_MODELS_DIRECTORY=${DLIB_MODELS_DIRECTORY}
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/github.com/diogox/dom-face-registry
    restart: on-failure
