version: 2
jobs:
    build:
      docker:
        - image: docker.io/ndphu/ubuntu-go-dlib
        - image: circleci/mongo:3.6.11
      steps:
        - checkout

        - restore_cache:
            keys:
              - proto-3.9.1

        - run:
            name: Install protoc
            environment:
              PROTOBUF_VERSION: '3.9.1'
            command: |
              apt install curl
              curl -OL https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip
              unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d protoc3
              mv protoc3/bin/* /usr/local/bin/
              mv protoc3/include/* /usr/local/include/

        - save_cache:
            key: proto-3.9.1
            paths:
            - protoc-3.9.1-linux-x86_64.zip

        - run:
            name: Generate files
            command: |
              go install github.com/golang/mock/mockgen
              go install github.com/golang/protobuf/protoc-gen-go
              go generate -mod vendor ./gen

        - run:
            name: Install dependencies
            command: go mod vendor

        - run:
            name: Run unit tests
            command: |
              go test ./...

        - setup_remote_docker

        - run:
            name: Install docker & docker-compose
            command: |
              apt-get update && apt install -y docker.io
              curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
              chmod +x ~/docker-compose
              mv ~/docker-compose /usr/local/bin/docker-compose

        - run:
            name: Start docker containers
            command: |
              docker-compose up -d --build
              docker ps -a
