// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person_registry.proto

package DomFaceRegistry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetPeopleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPeopleRequest) Reset()         { *m = GetPeopleRequest{} }
func (m *GetPeopleRequest) String() string { return proto.CompactTextString(m) }
func (*GetPeopleRequest) ProtoMessage()    {}
func (*GetPeopleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88844da4a24c054b, []int{0}
}

func (m *GetPeopleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeopleRequest.Unmarshal(m, b)
}
func (m *GetPeopleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeopleRequest.Marshal(b, m, deterministic)
}
func (m *GetPeopleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeopleRequest.Merge(m, src)
}
func (m *GetPeopleRequest) XXX_Size() int {
	return xxx_messageInfo_GetPeopleRequest.Size(m)
}
func (m *GetPeopleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeopleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeopleRequest proto.InternalMessageInfo

type GetPeopleResponse struct {
	People               []*Person `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPeopleResponse) Reset()         { *m = GetPeopleResponse{} }
func (m *GetPeopleResponse) String() string { return proto.CompactTextString(m) }
func (*GetPeopleResponse) ProtoMessage()    {}
func (*GetPeopleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88844da4a24c054b, []int{1}
}

func (m *GetPeopleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPeopleResponse.Unmarshal(m, b)
}
func (m *GetPeopleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPeopleResponse.Marshal(b, m, deterministic)
}
func (m *GetPeopleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPeopleResponse.Merge(m, src)
}
func (m *GetPeopleResponse) XXX_Size() int {
	return xxx_messageInfo_GetPeopleResponse.Size(m)
}
func (m *GetPeopleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPeopleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPeopleResponse proto.InternalMessageInfo

func (m *GetPeopleResponse) GetPeople() []*Person {
	if m != nil {
		return m.People
	}
	return nil
}

type AddPersonRequest struct {
	FirstName            string       `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string       `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Roles                []PersonRole `protobuf:"varint,3,rep,packed,name=roles,proto3,enum=DomFaceRegistry.PersonRole" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddPersonRequest) Reset()         { *m = AddPersonRequest{} }
func (m *AddPersonRequest) String() string { return proto.CompactTextString(m) }
func (*AddPersonRequest) ProtoMessage()    {}
func (*AddPersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88844da4a24c054b, []int{2}
}

func (m *AddPersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPersonRequest.Unmarshal(m, b)
}
func (m *AddPersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPersonRequest.Marshal(b, m, deterministic)
}
func (m *AddPersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPersonRequest.Merge(m, src)
}
func (m *AddPersonRequest) XXX_Size() int {
	return xxx_messageInfo_AddPersonRequest.Size(m)
}
func (m *AddPersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPersonRequest proto.InternalMessageInfo

func (m *AddPersonRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AddPersonRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *AddPersonRequest) GetRoles() []PersonRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AddPersonResponse struct {
	PersonId             string   `protobuf:"bytes,1,opt,name=person_id,json=personId,proto3" json:"person_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPersonResponse) Reset()         { *m = AddPersonResponse{} }
func (m *AddPersonResponse) String() string { return proto.CompactTextString(m) }
func (*AddPersonResponse) ProtoMessage()    {}
func (*AddPersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88844da4a24c054b, []int{3}
}

func (m *AddPersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPersonResponse.Unmarshal(m, b)
}
func (m *AddPersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPersonResponse.Marshal(b, m, deterministic)
}
func (m *AddPersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPersonResponse.Merge(m, src)
}
func (m *AddPersonResponse) XXX_Size() int {
	return xxx_messageInfo_AddPersonResponse.Size(m)
}
func (m *AddPersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPersonResponse proto.InternalMessageInfo

func (m *AddPersonResponse) GetPersonId() string {
	if m != nil {
		return m.PersonId
	}
	return ""
}

type RemovePersonRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePersonRequest) Reset()         { *m = RemovePersonRequest{} }
func (m *RemovePersonRequest) String() string { return proto.CompactTextString(m) }
func (*RemovePersonRequest) ProtoMessage()    {}
func (*RemovePersonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_88844da4a24c054b, []int{4}
}

func (m *RemovePersonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePersonRequest.Unmarshal(m, b)
}
func (m *RemovePersonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePersonRequest.Marshal(b, m, deterministic)
}
func (m *RemovePersonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePersonRequest.Merge(m, src)
}
func (m *RemovePersonRequest) XXX_Size() int {
	return xxx_messageInfo_RemovePersonRequest.Size(m)
}
func (m *RemovePersonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePersonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePersonRequest proto.InternalMessageInfo

func (m *RemovePersonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RemovePersonResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePersonResponse) Reset()         { *m = RemovePersonResponse{} }
func (m *RemovePersonResponse) String() string { return proto.CompactTextString(m) }
func (*RemovePersonResponse) ProtoMessage()    {}
func (*RemovePersonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_88844da4a24c054b, []int{5}
}

func (m *RemovePersonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePersonResponse.Unmarshal(m, b)
}
func (m *RemovePersonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePersonResponse.Marshal(b, m, deterministic)
}
func (m *RemovePersonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePersonResponse.Merge(m, src)
}
func (m *RemovePersonResponse) XXX_Size() int {
	return xxx_messageInfo_RemovePersonResponse.Size(m)
}
func (m *RemovePersonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePersonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePersonResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetPeopleRequest)(nil), "DomFaceRegistry.GetPeopleRequest")
	proto.RegisterType((*GetPeopleResponse)(nil), "DomFaceRegistry.GetPeopleResponse")
	proto.RegisterType((*AddPersonRequest)(nil), "DomFaceRegistry.AddPersonRequest")
	proto.RegisterType((*AddPersonResponse)(nil), "DomFaceRegistry.AddPersonResponse")
	proto.RegisterType((*RemovePersonRequest)(nil), "DomFaceRegistry.RemovePersonRequest")
	proto.RegisterType((*RemovePersonResponse)(nil), "DomFaceRegistry.RemovePersonResponse")
}

func init() { proto.RegisterFile("person_registry.proto", fileDescriptor_88844da4a24c054b) }

var fileDescriptor_88844da4a24c054b = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x69, 0x8b, 0x63, 0x3d, 0x83, 0xb9, 0xc5, 0x7f, 0xc3, 0x22, 0x8c, 0x80, 0xd0, 0xab,
	0xaa, 0xf3, 0x09, 0x84, 0xa1, 0x78, 0x23, 0x23, 0x2f, 0x30, 0xaa, 0x39, 0x4a, 0xa1, 0xed, 0x89,
	0x39, 0x51, 0xd8, 0xa5, 0x6f, 0x2e, 0x4b, 0xa2, 0x6c, 0x82, 0xb7, 0xbf, 0xef, 0xe3, 0xcb, 0x2f,
	0x07, 0x4e, 0x0c, 0x5a, 0xa6, 0x7e, 0x6d, 0xf1, 0xad, 0x61, 0x67, 0x37, 0x95, 0xb1, 0xe4, 0x48,
	0x1c, 0x2e, 0xa9, 0xbb, 0xaf, 0x5f, 0x50, 0x45, 0x7c, 0x3e, 0x72, 0x1b, 0x83, 0x1c, 0x52, 0x29,
	0x60, 0xf2, 0x80, 0x6e, 0x85, 0x64, 0x5a, 0x54, 0xf8, 0xfe, 0x81, 0xec, 0xe4, 0x12, 0xa6, 0x3b,
	0x8c, 0x0d, 0xf5, 0x8c, 0xe2, 0x0a, 0x06, 0xc6, 0x93, 0x59, 0x32, 0xcf, 0xca, 0xd1, 0xe2, 0xac,
	0xfa, 0xb3, 0x5b, 0xad, 0xfc, 0xf3, 0x2a, 0xd6, 0xe4, 0x57, 0x02, 0x93, 0x3b, 0xad, 0x23, 0x0d,
	0xd3, 0xe2, 0x02, 0xe0, 0xb5, 0xb1, 0xec, 0xd6, 0x7d, 0xdd, 0x6d, 0x97, 0x92, 0x32, 0x57, 0xb9,
	0x27, 0x4f, 0x75, 0x87, 0xa2, 0x80, 0xbc, 0xad, 0x7f, 0xd2, 0xd4, 0xa7, 0xc3, 0x2d, 0xf0, 0xe1,
	0x0d, 0x1c, 0x58, 0x6a, 0x91, 0x67, 0xd9, 0x3c, 0x2b, 0xc7, 0x8b, 0xe2, 0x3f, 0x01, 0x6a, 0x51,
	0x85, 0xa6, 0xbc, 0x86, 0xe9, 0x8e, 0x42, 0xfc, 0x49, 0x01, 0x79, 0xbc, 0x54, 0xa3, 0xa3, 0xc2,
	0x30, 0x80, 0x47, 0x2d, 0x2f, 0xe1, 0x48, 0x61, 0x47, 0x9f, 0xb8, 0xef, 0x3d, 0x86, 0xf4, 0xb7,
	0x9c, 0x36, 0x5a, 0x9e, 0xc2, 0xf1, 0x7e, 0x2d, 0x6c, 0x3f, 0x0f, 0xfc, 0x55, 0x6f, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xe0, 0xdd, 0x46, 0x14, 0x8c, 0x01, 0x00, 0x00,
}
