// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package DomFaceRegistry

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersonRole int32

const (
	PersonRole_INHABITANT    PersonRole = 0
	PersonRole_GUEST         PersonRole = 1
	PersonRole_TRANSIENT     PersonRole = 2
	PersonRole_FAMILY_MEMBER PersonRole = 3
)

var PersonRole_name = map[int32]string{
	0: "INHABITANT",
	1: "GUEST",
	2: "TRANSIENT",
	3: "FAMILY_MEMBER",
}

var PersonRole_value = map[string]int32{
	"INHABITANT":    0,
	"GUEST":         1,
	"TRANSIENT":     2,
	"FAMILY_MEMBER": 3,
}

func (x PersonRole) String() string {
	return proto.EnumName(PersonRole_name, int32(x))
}

func (PersonRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

type FaceImage struct {
	ImageData            []byte   `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaceImage) Reset()         { *m = FaceImage{} }
func (m *FaceImage) String() string { return proto.CompactTextString(m) }
func (*FaceImage) ProtoMessage()    {}
func (*FaceImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *FaceImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceImage.Unmarshal(m, b)
}
func (m *FaceImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceImage.Marshal(b, m, deterministic)
}
func (m *FaceImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceImage.Merge(m, src)
}
func (m *FaceImage) XXX_Size() int {
	return xxx_messageInfo_FaceImage.Size(m)
}
func (m *FaceImage) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceImage.DiscardUnknown(m)
}

var xxx_messageInfo_FaceImage proto.InternalMessageInfo

func (m *FaceImage) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

type Person struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string       `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string       `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Roles                []PersonRole `protobuf:"varint,4,rep,packed,name=roles,proto3,enum=DomFaceRegistry.PersonRole" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Person) GetRoles() []PersonRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterEnum("DomFaceRegistry.PersonRole", PersonRole_name, PersonRole_value)
	proto.RegisterType((*FaceImage)(nil), "DomFaceRegistry.FaceImage")
	proto.RegisterType((*Person)(nil), "DomFaceRegistry.Person")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x10, 0xc7, 0x6d, 0xeb, 0x86, 0x39, 0x5d, 0xad, 0x79, 0x2a, 0x0c, 0x61, 0xec, 0x69, 0xec, 0xa1,
	0xa0, 0x7e, 0x82, 0x8e, 0x75, 0x1a, 0xb0, 0x41, 0xb2, 0xf8, 0xe0, 0x53, 0x89, 0xf6, 0x1c, 0x81,
	0x76, 0x19, 0x49, 0x5e, 0xf6, 0x09, 0xfc, 0xda, 0xd2, 0x0c, 0x11, 0xf6, 0x76, 0xf7, 0xfb, 0xfd,
	0x8f, 0x3b, 0x0e, 0xae, 0xfd, 0xf1, 0x80, 0xae, 0x38, 0x58, 0xe3, 0x0d, 0xbd, 0x5d, 0x9b, 0x7e,
	0xa3, 0xbe, 0x50, 0xe0, 0x4e, 0x3b, 0x6f, 0x8f, 0xf3, 0x25, 0x90, 0xa1, 0x67, 0xbd, 0xda, 0x21,
	0xbd, 0x07, 0xd0, 0x43, 0xd1, 0xb4, 0xca, 0xab, 0x3c, 0x9a, 0x45, 0x8b, 0x1b, 0x41, 0x02, 0x59,
	0x2b, 0xaf, 0xe6, 0x3f, 0x11, 0x8c, 0xdf, 0xd0, 0x3a, 0xb3, 0xa7, 0x29, 0xc4, 0xba, 0x0d, 0x09,
	0x22, 0x62, 0xdd, 0x0e, 0x93, 0xdf, 0xda, 0x3a, 0xdf, 0xec, 0x55, 0x8f, 0x79, 0x1c, 0x38, 0x09,
	0x84, 0xab, 0x1e, 0xe9, 0x14, 0x48, 0xa7, 0xfe, 0x6c, 0x12, 0xec, 0xd5, 0x00, 0x82, 0x7c, 0x80,
	0x91, 0x35, 0x1d, 0xba, 0xfc, 0x72, 0x96, 0x2c, 0xd2, 0xc7, 0x69, 0x71, 0x76, 0x63, 0x71, 0xda,
	0x29, 0x4c, 0x87, 0xe2, 0x94, 0x5c, 0x32, 0x80, 0x7f, 0x48, 0x53, 0x00, 0xc6, 0x5f, 0xca, 0x15,
	0x93, 0x25, 0x97, 0xd9, 0x05, 0x25, 0x30, 0x7a, 0x7e, 0xaf, 0xb6, 0x32, 0x8b, 0xe8, 0x04, 0x88,
	0x14, 0x25, 0xdf, 0xb2, 0x8a, 0xcb, 0x2c, 0xa6, 0x77, 0x30, 0xd9, 0x94, 0x35, 0x7b, 0xfd, 0x68,
	0xea, 0xaa, 0x5e, 0x55, 0x22, 0x4b, 0x3e, 0xc7, 0xe1, 0x31, 0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x5e, 0x01, 0x6b, 0xf7, 0x27, 0x01, 0x00, 0x00,
}
